### ISSUE TITLE
Adjust the UI design of the projector screen

### ISSUE THREAD

**Issue by CircuitCoder** [CircuitCoder/Console-Lite#8]
It has been mentioned by delegates to me several times that the bottom part of the projector screen is hard to see from the back of conference halls, where all the key information lies. I suggest move the bar to the top entirely, and fix this problem once and for all.

**Comment by JieJiSS** [comment]
Hey, it's me again. I'm at BJMUNC2018 now and after the first session, I discussed with the Dais about Console-Lite. They told me that the `text-overflow: ellipsis;` rule of the Motion Topic is quite annoying, and I think that maybe add a `:hover` selector (or even an `onmousein` event) to let it expand itself is a possible solution. What's more, the Dais think that when adding a new Motion, it's a good idea for the prompt window to contain a `Sponsor` inputarea and a `sponsor speak at last` checkbox so that they will not have to achieve these by adding the sponsor country at last manually. I have forked this repo already , but I'm not sure when can I finish all these --- since I'm not quite used to Vue. 
Thanks for making such a genius software.

**Comment by CircuitCoder** [comment]
@JieJiSS Thanks for your suggestion.

The primary concern of removing the `text-overflow: ellipsis;` is that text do overflow at times. One idea is to reduce the size of the font, which may also leads to readability problems. The problem with the hover-to-show solution is that Dias spend most of their time operating in the controller window, so hovering on the projector window involves a lot of mouse movement, which is not convenient.

We may add an additional behavior: clicking on the title in the controller window will toggle the expansion of title sections in the projector window. This is not so intuitive, but I think this is not a frequently-used functionality either, so a tooltip may be enough for teaching Dias how to use it.

Also in my opinion, the title of the conference is the least important information for any delegate, which means showing them on the projector screen somewhat meaningless. So if that's just not so pretty for our eyes, we may just remove them.

As for the sponsor text area, it doesn't reduce any complexity of adding a new speaker. The sponsor behaves just like other speakers in the speaker lists, so adding them should behaves just like adding the other speakers.

I may want to mention that, pushing Shift+Enter while adding an speaker will immediately finish the current one and start adding a new one. **Drag & Drop with speakers can reorder them**, and clicking on one speaker can modify it. I believe many of these functionalities is not widely known, because of the lack of documentation (and the reading of them).

**Comment by CircuitCoder** [comment]
@JieJiSS Oh sorry, so you are saying the motions' topic, not the conference title. Then I guess we need to stick with the third solution.

**Comment by JieJiSS** [comment]
@CircuitCoder 👌that's a very nice solution 
Thanks a lot

**Comment by CircuitCoder** [comment]
This will be closed without fixing, because the changing of design violate the theme of the software too much, and also creates an sense of imbalance (See the screenshot attached below).

![top-bar](https://user-images.githubusercontent.com/2051572/44014509-f1aac5c0-9efe-11e8-8c61-9e2022f671cf.png)

This is a wont-fix.
